version: '2'
services:
  tomcat:
    build: ./tomcat/
    environment:
    - CATALINA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
    ports: 
      - '8888:8080'
      - '8000:8000'
    volumes:
      - ../web-chat-rooms-webapp/target:/home/webchatrooms/chatrooms-webapp
    command: ['catalina.sh', 'run']
